version: '3'

tasks:
  up:
    desc: "Starts the local backing services"
    cmds:
      - docker compose up -d --wait --wait-timeout 3000
      - task: pulumi
        
  pulumi:
    desc: "Runs pulumi"
    dir: ../../Support/Infra.Code
    internal: true
    env:
      PULUMI_CONFIG_PASSPHRASE: "1234567"
    cmds:
      - pwd
      - pulumi up --yes --skip-preview
  down:
    desc: "Stops the local backing services"
    cmds:
      - docker-compose down -v
  ps:
    cmds:
      - docker-compose ps
  shell:database:
    interactive: true
    cmds:
      - docker-compose exec postgres bash