version: '3'

includes:
  coverage:
    taskfile: ../.github/workflows/tasks/DotnetCoverage.yml
    dir: "{{.USER_WORKING_DIR}}"
    internal: true

tasks:
  build:
    cmds:
      - task: build:project
        vars:
          PROJECT: "Gatekeeper.Core"
  
  build:test:
    cmds:
      - task: build:project
        vars:
          PROJECT: "Gatekeeper.Core.Test"
  test:
    deps:
      - build:test
    cmds:
      - dotnet test Gatekeeper.Core.Test/
  
  test:coverage:
    desc: "Run coverage for core"
    deps:
      - build:test
    cmds:
      - task: coverage:run
        vars:
          TEST_CMD: "dotnet test Gatekeeper.Core.Test/"
          TEST_OUTPUT: "coverage.core.xml"
  
  build:project:
    internal: true
    cmds:
      - dotnet build {{.PROJECT}}/    